// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7FT-tt2KMwtzyWkbcvbdFheCbkXK9_GA',
    appId: '1:798439543350:web:5edd095417b6f17ef7fe97',
    messagingSenderId: '798439543350',
    projectId: 'ubber-8f8e8',
    authDomain: 'ubber-8f8e8.firebaseapp.com',
    storageBucket: 'ubber-8f8e8.firebasestorage.app',
    measurementId: 'G-3QDR2LLPTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fE25g3450MNr4R1p-ratqB7lGEJXBRE',
    appId: '1:798439543350:android:9ba73db087d49268f7fe97',
    messagingSenderId: '798439543350',
    projectId: 'ubber-8f8e8',
    storageBucket: 'ubber-8f8e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJpsHlH4NUNOEgvT7qOnfJMnzHO_ILk7g',
    appId: '1:798439543350:ios:b1e28641409a1031f7fe97',
    messagingSenderId: '798439543350',
    projectId: 'ubber-8f8e8',
    storageBucket: 'ubber-8f8e8.firebasestorage.app',
    iosBundleId: 'com.example.ubberclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJpsHlH4NUNOEgvT7qOnfJMnzHO_ILk7g',
    appId: '1:798439543350:ios:b1e28641409a1031f7fe97',
    messagingSenderId: '798439543350',
    projectId: 'ubber-8f8e8',
    storageBucket: 'ubber-8f8e8.firebasestorage.app',
    iosBundleId: 'com.example.ubberclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7FT-tt2KMwtzyWkbcvbdFheCbkXK9_GA',
    appId: '1:798439543350:web:10ab605d1f5d6762f7fe97',
    messagingSenderId: '798439543350',
    projectId: 'ubber-8f8e8',
    authDomain: 'ubber-8f8e8.firebaseapp.com',
    storageBucket: 'ubber-8f8e8.firebasestorage.app',
    measurementId: 'G-8JRXKB75RX',
  );
}
